#!/bin/sh
# This file is called ~/batchdetect.sh
# This is a batch script to run the detections with the following params:
# to debug use: bash -x batchdetect.sh


############################################################
# SPECIFYING COMMON VARS USED FOR TESTRUNS
############################################################

# PROJ_ROOT gives path to the shell script.
# PROJ_ROOT="car-classifier-research/src/hyp.verification.tools/
# PROJ_ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )" # this gets path to script

# PROJ_ROOT gives path to the git home.
# PROJ_ROOT="car-classifier-research
PROJ_ROOT="$( git rev-parse --show-toplevel )"

# the detection script to use
DETECT_SCRIPT=$PROJ_ROOT"/src/hyp.verification.tools/py/detect.py"
# the testdata location
TESTDATA_DIR=$PROJ_ROOT"/testdata"

# the locations of the test sets of images
TESTDATA_IMG_FB_TRAINSET=$TESTDATA_DIR"/frontbacks/trainingset.focused/"
TESTDATA_IMG_FB_TESTSET=$TESTDATA_DIR"/frontbacks/testset/"
TESTDATA_IMG_FB_PDSET=$TESTDATA_DIR"/frontbacks/publicdomainset/"
TESTDATA_IMG_S_TRAINSET=$TESTDATA_DIR"/sides/trainingset.focused/"
TESTDATA_IMG_S_TESTSET=$TESTDATA_DIR"/sides/testset/"
# TESTDATA_IMG_S_PDSET=$TESTDATA_DIR"/sides/publicdomainset/"

# with noise added
TESTDATA_IMG_FB_TRAINSET_NOISY=$TESTDATA_DIR"/frontbacks/trainingset.focused.noisy/"
TESTDATA_IMG_FB_TESTSET_NOISY=$TESTDATA_DIR"/frontbacks/testset.noisy/"
TESTDATA_IMG_FB_PDSET_NOISY=$TESTDATA_DIR"/frontbacks/publicdomainset.noisy/"
TESTDATA_IMG_S_TRAINSET_NOISY=$TESTDATA_DIR"/sides/trainingset.focused.noisy/"
TESTDATA_IMG_S_TESTSET_NOISY=$TESTDATA_DIR"/sides/testset.noisy/"
# TESTDATA_IMG_S_PDSET_NOISY=$TESTDATA_DIR"/sides/publicdomainset.noisy/"

# where to put the results
TEST_RESULTS_DIR=$PROJ_ROOT"/testresults"
TEST_RESULTS_DIR_FB=$PROJ_ROOT"/testresults/frontbacks/"
TEST_RESULTS_DIR_S=$PROJ_ROOT"/testresults/sides/"

LOG_RESULTS_DIR=$TEST_RESULTS_DIR
IMG_RESULTS_DIR=$TEST_RESULTS_DIR

# path to directories containing the classifiers
CLASSIFIER_DIR_S=$PROJ_ROOT"/trained_classifiers/sides"
CLASSIFIER_DIR_FB=$PROJ_ROOT"/trained_classifiers/frontbacks"

# the classifiers
CLASSIFIER_FB_HAAR=$CLASSIFIER_DIR_FB"/haar.gab.24x20s_fb.xml"
CLASSIFIER_FB_HOG=$CLASSIFIER_DIR_FB"/hog.gab.24x20s_fb.xml"
CLASSIFIER_FB_LBP=$CLASSIFIER_DIR_FB"/lbp.gab.24x20s_fb.xml"
CLASSIFIER_FB_CARS=$CLASSIFIER_DIR_FB"/cars3.xml"
CLASSIFIER_FB_HOG_35=$CLASSIFIER_DIR_FB"/hog.gab.24x35s_fb.xml"

CLASSIFIER_S_HAAR=$CLASSIFIER_DIR_S"/haar.gab.24x20s_side.xml"
CLASSIFIER_S_HOG=$CLASSIFIER_DIR_S"/hog.gab.24x20s_side.xml"
CLASSIFIER_S_LBP=$CLASSIFIER_DIR_S"/lbp.gab.24x20s_side.xml"
CLASSIFIER_S_CARS=$CLASSIFIER_DIR_FB"/cars3.xml"

# rabs
CLASSIFIER_FB_HAAR_R=$CLASSIFIER_DIR_FB"/haar.rab.24x20s_fb.xml"
CLASSIFIER_FB_HOG_R=$CLASSIFIER_DIR_FB"/hog.rab.24x20s_fb.xml"
CLASSIFIER_FB_LBP_R=$CLASSIFIER_DIR_FB"/lbp.rab.24x20s_fb.xml"
CLASSIFIER_FB_HOG_R_35=$CLASSIFIER_DIR_FB"/hog.rab.24x35s_fb.xml"





# path to groundtruth labelled data
LABELLED_DATA_DIR_FB=$TESTDATA_DIR"/frontbacks/labelled.groundtruths"
LABELLED_DATA_DIR_S=$TESTDATA_DIR"/sides/labelled.groundtruths"

# the labelled data files.
LABELLED_DATA_DIR_FB_TRAIN=$LABELLED_DATA_DIR_FB/"trainingset_100.txt"
LABELLED_DATA_DIR_FB_TEST=$LABELLED_DATA_DIR_FB/"testset_100.txt"
LABELLED_DATA_DIR_FB_PD=$LABELLED_DATA_DIR_FB/"publicdomainset_25.txt"
LABELLED_DATA_DIR_S_TRAIN=$LABELLED_DATA_DIR_S/"uiuc_trainset_100.txt"
LABELLED_DATA_DIR_S_TEST=$LABELLED_DATA_DIR_S/"uiuc_100.txt"

# the colorspace to detect in (default should be $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE others mightnt be accurate.)
COLORSPACE="gray"




############################################################
# CALL THE TESTRUNS
############################################################

# a run is specified as format:
# python $path_to_detect_script $path_to_test_images_directory $path_to_classifier $path_to_labelled_groundtruths $path_to_save_images_after_detection $path_to_save_txtfile_after_detection $COLORSPACE number_of_min_neighbors test_type_F_or_S

# iterate through MN = 2,4,6,8,10
# running each detection with the given classifier.

#### FRONTBACKS ####
# for MN in {2..10..2}
# 	do
		# test each front classifier on the training, test and PD sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		#
		# # do the same for the noisy sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HAAR $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HOG $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_LBP $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_CARS $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F


		######### rab 20s ##########

		# test each front classifier on the training, test and PD sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# # do the same for the noisy sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HAAR_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HOG_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_LBP_R $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F

		############### the two 35 hogs ##########
		# test each front classifier on the training, test and PD sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# # do the same for the noisy sets.
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TRAINSET_NOISY $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_TRAIN $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_TESTSET_NOISY $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_TEST $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HOG_35 $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F
		# python $DETECT_SCRIPT $TESTDATA_IMG_FB_PDSET_NOISY $CLASSIFIER_FB_HOG_R_35 $LABELLED_DATA_DIR_FB_PD $TEST_RESULTS_DIR_FB $TEST_RESULTS_DIR_FB $COLORSPACE $MN F

# done

# #### SIDES ####
for MN in {2..10..2}

	do
		# : # pass

		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET $CLASSIFIER_S_HAAR $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET $CLASSIFIER_S_LBP $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET $CLASSIFIER_S_CARS $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET $CLASSIFIER_S_HAAR $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET $CLASSIFIER_S_LBP $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET $CLASSIFIER_S_CARS $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		#
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET_NOISY $CLASSIFIER_S_HAAR $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET_NOISY $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET_NOISY $CLASSIFIER_S_LBP $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		# python $DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET_NOISY $CLASSIFIER_S_CARS $LABELLED_DATA_DIR_S_TRAIN $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S

		python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET_NOISY $CLASSIFIER_S_HAAR $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET_NOISY $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET_NOISY $CLASSIFIER_S_LBP $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
		python $DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET_NOISY $CLASSIFIER_S_CARS $LABELLED_DATA_DIR_S_TEST $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE $MN S
done





############################################################
# BELOW USED FOR DEBUGGING
############################################################
# echo "params used for Side Run: "
# echo "DETECT_SCRIPT: $DETECT_SCRIPT"
# echo "TESTDATA_IMG_S_TRAINSET: $TESTDATA_IMG_S_TRAINSET"
# echo "CLASSIFIER_DIR_S: $CLASSIFIER_DIR_S/haar.gab.24x20s_side.xml"
# echo "LABELLED_DATA_DIR_S: $LABELLED_DATA_DIR_S/uiuc_trainset_100.txt"
# echo "TEST_RESULTS_DIR_S: $TEST_RESULTS_DIR_S"
# echo "TEST_RESULTS_DIR_S: $TEST_RESULTS_DIR_S"
# echo "where to save images: $TESTDATA_IMG_S_TRAINSET"
# echo "where to save txt file results: $TESTDATA_IMG_S_TRAINSET"
# echo "colorspace to used: $COLORSPACE"
# echo "minneighbors used: 2"
# echo "testtype: S"
#
#
# echo "params used for Frontback run: "
# echo "DETECT_SCRIPT: $DETECT_SCRIPT"
# echo "TESTDATA_IMG_FB_TRAINSET: $TESTDATA_IMG_FB_TRAINSET"
# echo "CLASSIFIER_DIR_FB the classifier: $CLASSIFIER_DIR_FB/haar.gab.24x20s_fb.xml"
# echo "LABELLED_DATA_DIR_FB: $LABELLED_DATA_DIR_FB/uiuc_trainset_100.txt"
# echo "TEST_RESULTS_DIR_FB: $TEST_RESULTS_DIR_FB"
# echo "TEST_RESULTS_DIR_FB: $TEST_RESULTS_DIR_FB"
# echo "where to save images: $TESTDATA_IMG_FB_TRAINSET"
# echo "where to save txt file results: $TESTDATA_IMG_FB_TRAINSET"
# echo "colorspace to used: $COLORSPACE"
# echo "minneighbors used: 2"
# echo "testtype: F"

############################################################
# TODO: write params to file for easier debugging.
# testset_run=$DETECT_SCRIPT $TESTDATA_IMG_S_TESTSET $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S"/uiuc_100.txt" $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE 2 S
# trainset_run=$DETECT_SCRIPT $TESTDATA_IMG_S_TRAINSET $CLASSIFIER_S_HOG $LABELLED_DATA_DIR_S"/uiuc_trainset_100.txt" $TEST_RESULTS_DIR_S $TEST_RESULTS_DIR_S $COLORSPACE 2 S
# python echo $testset_run
# python echo $trainset_run


# #get rid of any existing file (optional)
# rm lastbatchrun_params.txt 2>/$PROJ_ROOT/lastbatchrun_params.txt
# echo "testset_run_params = $testset_run" >>lastbatchrun_params.txt
# echo "trainset_run_params = $trainset_run" >>lastbatchrun_params.txt
